In [2]:
from kedro_mlflow.io.metrics import MlflowMetricDataset

In [1]:
pip show kedro-mlflow

Note: you may need to restart the kernel to use updated packages.

c:\Users\avril\Octavo_semestre\Reto-TCA-Series-de-tiempo\my-kedro-project\tca-pipeline\.venv\Scripts\python.exe: No module named pip

In [2]:
from kedro_mlflow.framework.hooks import MlflowHook
mlflow_hook = MlflowHook()
HOOKS = (mlflow_hook,)

[05/28/25 21:04:24] INFO     Using 'conf\logging.yml' as logging configuration. You can change this ]8;id=748840;file://c:\Users\avril\Octavo_semestre\Reto-TCA-Series-de-tiempo\my-kedro-project\tca-pipeline\.venv\Lib\site-packages\kedro\framework\project\__init__.py\__init__.py]8;;\:]8;id=725699;file://c:\Users\avril\Octavo_semestre\Reto-TCA-Series-de-tiempo\my-kedro-project\tca-pipeline\.venv\Lib\site-packages\kedro\framework\project\__init__.py#272\272]8;;\
                             by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.

c:\Users\avril\Octavo_semestre\Reto-TCA-Series-de-tiempo\my-kedro-project\tca-pipeline\.venv\Lib\site-packages\mlflow\pyfunc\utils\data_validation.py:186: UserWarning: Add type hints to the `predict` method to enable data validation and automatic signature inference during model logging. Check https://mlflow.org/docs/latest/model/python_model.html#type-hint-usage-in-pythonmodel for more details.
  color_warning(

In [1]:
filepath = "data/01_raw/reservaciones_tcabdfront2.csv"

In [2]:
import pandas as pd

df = pd.read_csv(filepath)

df.tail(10000)

C:\Users\avril\AppData\Local\Temp\ipykernel_11336\1556847419.py:3: DtypeWarning: Columns (22,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filepath)

,ID_Reserva,Fecha_hoy,h_res_fec,h_res_fec_ok,h_res_fec_okt,h_num_per,aa_h_num_per,h_num_adu,aa_h_num_adu,h_num_men,...,h_edo,h_codigop,h_correo_e,h_nom,h_tfa_total,aa_h_tfa_total,moneda_cve,h_ult_cam_fec,h_ult_cam_fec_ok,h_ult_cam_fec_okt
193002,193002,2020-02-18 00:00:00.000,20190218,2019-02-18,2019-02-18 00:00:00.000,0,2,0,2,0,...,EGR,40880,NaN,NaN,0.0,6560.00,1,20191109,2019-11-09,2019-11-09 00:00:00.000
193003,193003,2020-02-18 00:00:00.000,20190218,2019-02-18,2019-02-18 00:00:00.000,0,2,0,2,0,...,EGR,40880,NaN,NaN,0.0,6560.00,1,20191109,2019-11-09,2019-11-09 00:00:00.000
193004,193004,2020-02-18 00:00:00.000,20190218,2019-02-18,2019-02-18 00:00:00.000,0,3,0,3,0,...,EGR,40880,NaN,NaN,0.0,9540.00,1,20191109,2019-11-09,2019-11-09 00:00:00.000
193005,193005,2020-02-18 00:00:00.000,20190218,2019-02-18,2019-02-18 00:00:00.000,0,3,0,2,0,...,EGR,40880,NaN,NaN,0.0,7458.00,1,20191109,2019-11-09,2019-11-09 00:00:00.000
193006,193006,2020-03-14 00:00:00.000,20190314,2019-03-14,2019-03-14 00:00:00.000,0,1,0,1,0,...,EMX,06700,NaN,NaN,0.0,10755.00,1,20190324,2019-03-24,2019-03-24 00:00:00.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202997,202997,2020-04-10 00:00:00.000,20190410,2019-04-10,2019-04-10 00:00:00.000,0,2,0,2,0,...,EMC,58197,NaN,NaN,0.0,2659.95,1,20190410,2019-04-10,2019-04-10 00:00:00.000
202998,202998,2020-06-17 00:00:00.000,20190617,2019-06-17,2019-06-17 00:00:00.000,0,2,0,2,0,...,EGR,5165165,NaN,NaN,0.0,171.00,1,20190617,2019-06-17,2019-06-17 00:00:00.000
202999,202999,2020-05-30 00:00:00.000,20190530,2019-05-30,2019-05-30 00:00:00.000,0,3,0,2,0,...,EMC,60110,NaN,NaN,0.0,2659.98,1,20190602,2019-06-02,2019-06-02 00:00:00.000
203000,203000,2020-08-10 00:00:00.000,20190810,2019-08-10,2019-08-10 00:00:00.000,0,2,0,2,0,...,EMC,60432,NaN,NaN,0.0,7900.96,1,20190812,2019-08-12,2019-08-12 00:00:00.000
203001,203001,2020-02-24 00:00:00.000,20190224,2019-02-24,2019-02-24 00:00:00.000,0,2,0,2,0,...,EMC,61606,NaN,NaN,0.0,2212.00,1,20190228,2019-02-28,2019-02-28 00:00:00.000

In [3]:
df.columns

Index(['ID_Reserva', 'Fecha_hoy', 'h_res_fec', 'h_res_fec_ok', 'h_res_fec_okt',
       'h_num_per', 'aa_h_num_per', 'h_num_adu', 'aa_h_num_adu', 'h_num_men',
       'aa_h_num_men', 'h_num_noc', 'aa_h_num_noc', 'h_tot_hab',
       'aa_h_tot_hab', 'ID_Programa', 'ID_Paquete', 'ID_Segmento_Comp',
       'ID_Agencia', 'ID_empresa', 'ID_Tipo_Habitacion', 'ID_canal',
       'h_fec_lld', 'h_fec_lld_ok', 'h_fec_lld_okt', 'h_fec_reg',
       'h_fec_reg_ok', 'h_fec_reg_okt', 'h_fec_sda', 'h_fec_sda_ok',
       'h_fec_sda_okt', 'ID_Pais_Origen', 'Cliente_Disp', 'aa_Cliente_Disp',
       'Reservacion', 'aa_Reservacion', 'ID_estatus_reservaciones',
       'h_can_res', 'h_cod_reserva', 'h_edo', 'h_codigop', 'h_correo_e',
       'h_nom', 'h_tfa_total', 'aa_h_tfa_total', 'moneda_cve', 'h_ult_cam_fec',
       'h_ult_cam_fec_ok', 'h_ult_cam_fec_okt'],
      dtype='object')

In [4]:
import pandas as pd

# Ruta donde Kedro buscará los datos de inferencia
inference_filepath = "data/01_raw/reservaciones_inference.csv"

df_filtrado = df[df["h_tot_hab"] > 0]
# Filtrar las últimas 100 filas
df_inference = df_filtrado.tail(100)

# Guardar el archivo CSV sin el índice
df_inference.to_csv(inference_filepath, index=False)

In [5]:
df_inference.shape

(100, 49)

In [6]:
import numpy as np
import pandas as pd

# Reemplaza inf, -inf por NaN (por si los hay)
df_inference = df_inference.replace([np.inf, -np.inf], np.nan)

# Luego, reemplaza todos los NaN por un valor numérico válido (por ejemplo, 0 o -1)
df_inference = df_inference.fillna(0)  # puedes usar -1 si prefieres

# También puedes hacer esto si quieres solo limpiar columnas específicas
# df_inference["col1"] = df_inference["col1"].fillna(0)
df_inference.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 102099 to 102198
Data columns (total 49 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID_Reserva                100 non-null    int64
 1   Fecha_hoy                 100 non-null    object
 2   h_res_fec                 100 non-null    int64
 3   h_res_fec_ok              100 non-null    object
 4   h_res_fec_okt             100 non-null    object
 5   h_num_per                 100 non-null    int64
 6   aa_h_num_per              100 non-null    int64
 7   h_num_adu                 100 non-null    int64
 8   aa_h_num_adu              100 non-null    int64
 9   h_num_men                 100 non-null    int64
 10  aa_h_num_men              100 non-null    int64
 11  h_num_noc                 100 non-null    int64
 12  aa_h_num_noc              100 non-null    int64
 13  h_tot_hab                 100 non-null    int64
 14  aa_h_tot_hab              100 non-null    int64
 15  ID_Programa               100 non-null    int64
 16  ID_Paquete                100 non-null    int64
 17  ID_Segmento_Comp          100 non-null    int64
 18  ID_Agencia                100 non-null    int64
 19  ID_empresa                100 non-null    int64
 20  ID_Tipo_Habitacion        100 non-null    int64
 21  ID_canal                  100 non-null    int64
 22  h_fec_lld                 100 non-null    int64
 23  h_fec_lld_ok              100 non-null    object
 24  h_fec_lld_okt             100 non-null    object
 25  h_fec_reg                 100 non-null    object
 26  h_fec_reg_ok              100 non-null    object
 27  h_fec_reg_okt             100 non-null    object
 28  h_fec_sda                 100 non-null    int64
 29  h_fec_sda_ok              100 non-null    object
 30  h_fec_sda_okt             100 non-null    object
 31  ID_Pais_Origen            100 non-null    int64
 32  Cliente_Disp              100 non-null    int64
 33  aa_Cliente_Disp           100 non-null    int64
 34  Reservacion               100 non-null    int64
 35  aa_Reservacion            100 non-null    int64
 36  ID_estatus_reservaciones  100 non-null    int64
 37  h_can_res                 100 non-null    object
 38  h_cod_reserva             100 non-null    object
 39  h_edo                     100 non-null    object
 40  h_codigop                 100 non-null    object
 41  h_correo_e                100 non-null    float64
 42  h_nom                     100 non-null    float64
 43  h_tfa_total               100 non-null    float64
 44  aa_h_tfa_total            100 non-null    float64
 45  moneda_cve                100 non-null    int64
 46  h_ult_cam_fec             100 non-null    object
 47  h_ult_cam_fec_ok          100 non-null    object
 48  h_ult_cam_fec_okt         100 non-null    object
dtypes: float64(4), int64(28), object(17)
memory usage: 39.1+ KB

C:\Users\avril\AppData\Local\Temp\ipykernel_11336\2245664142.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_inference = df_inference.replace([np.inf, -np.inf], np.nan)

In [7]:
import requests

# Convertir a lista de diccionarios
data_dict = df_inference.to_dict(orient="records")
payload = { "data": data_dict }

# Enviar POST
url = "http://localhost:8080/predict"
response = requests.post(url, json=payload)

# Mostrar resultados
if response.status_code == 200:
    print("✅ Predicciones:")
    print(response.json())
else:
    print("❌ Error:", response.status_code)
    print(response.text)

✅ Predicciones:
{'predictions': [{'ds': '2021-05-02', 'yhat': 315.9443588052453, 'yhat_lower': 175.4385645712364, 'yhat_upper': 467.2116485242354}, {'ds': '2021-05-03', 'yhat': 358.6163850182446, 'yhat_lower': 210.83135798136223, 'yhat_upper': 500.28009044367184}, {'ds': '2021-05-04', 'yhat': 352.41068140559025, 'yhat_lower': 220.64813915188967, 'yhat_upper': 495.0602003254493}, {'ds': '2021-05-05', 'yhat': 274.54061713629153, 'yhat_lower': 120.53408348174347, 'yhat_upper': 418.33249476008547}, {'ds': '2021-05-06', 'yhat': 313.13026403999294, 'yhat_lower': 170.42369443155107, 'yhat_upper': 450.3870886054209}, {'ds': '2021-05-07', 'yhat': 468.3381190896774, 'yhat_lower': 325.14702826871417, 'yhat_upper': 610.4899811336783}, {'ds': '2021-05-08', 'yhat': 470.20900682274726, 'yhat_lower': 324.86515231531797, 'yhat_upper': 618.2154529138153}, {'ds': '2021-05-09', 'yhat': 328.4238677674505, 'yhat_lower': 182.79262390541763, 'yhat_upper': 464.4783824262867}, {'ds': '2021-05-10', 'yhat': 369.9276177399973, 'yhat_lower': 222.17365315381406, 'yhat_upper': 512.7065060520387}, {'ds': '2021-05-11', 'yhat': 362.4439889141645, 'yhat_lower': 213.7281014900067, 'yhat_upper': 506.44692511371255}, {'ds': '2021-05-12', 'yhat': 283.1448297749719, 'yhat_lower': 132.95130674127688, 'yhat_upper': 414.9084345073855}, {'ds': '2021-05-13', 'yhat': 320.149794005873, 'yhat_lower': 181.32503017196612, 'yhat_upper': 457.0192744085073}, {'ds': '2021-05-14', 'yhat': 473.61676917036084, 'yhat_lower': 322.0871240154859, 'yhat_upper': 617.9990209988661}, {'ds': '2021-05-15', 'yhat': 473.59373585060604, 'yhat_lower': 345.95332495300414, 'yhat_upper': 627.4649997874687}, {'ds': '2021-05-16', 'yhat': 329.77820015628777, 'yhat_lower': 191.9791486060115, 'yhat_upper': 488.6907002638151}, {'ds': '2021-05-17', 'yhat': 369.1498248539107, 'yhat_lower': 217.75204951116476, 'yhat_upper': 509.27138905692095}, {'ds': '2021-05-18', 'yhat': 359.40365118043, 'yhat_lower': 213.72803812939313, 'yhat_upper': 502.7956328789264}, {'ds': '2021-05-19', 'yhat': 277.77167916240984, 'yhat_lower': 136.37623422913853, 'yhat_upper': 415.3011891334321}, {'ds': '2021-05-20', 'yhat': 312.4107528909772, 'yhat_lower': 177.0362169532531, 'yhat_upper': 457.9071706128493}, {'ds': '2021-05-21', 'yhat': 463.51901958049336, 'yhat_lower': 324.0370577299842, 'yhat_upper': 610.0999117145626}, {'ds': '2021-05-22', 'yhat': 461.18617222133537, 'yhat_lower': 320.2687658807582, 'yhat_upper': 603.3990183722926}, {'ds': '2021-05-23', 'yhat': 315.1568891281186, 'yhat_lower': 175.5277146693866, 'yhat_upper': 465.20895405235785}, {'ds': '2021-05-24', 'yhat': 352.46266448500944, 'yhat_lower': 203.84392276897444, 'yhat_upper': 491.6764980289754}, {'ds': '2021-05-25', 'yhat': 340.845777131773, 'yhat_lower': 197.67292982259482, 'yhat_upper': 492.2377242779896}, {'ds': '2021-05-26', 'yhat': 257.58659660875634, 'yhat_lower': 112.89931785834644, 'yhat_upper': 394.03426667088684}, {'ds': '2021-05-27', 'yhat': 290.8901526867521, 'yhat_lower': 161.66305532409308, 'yhat_upper': 438.7143912634444}, {'ds': '2021-05-28', 'yhat': 440.99763042839874, 'yhat_lower': 301.37915267544906, 'yhat_upper': 584.4508009373184}, {'ds': '2021-05-29', 'yhat': 438.03459176850185, 'yhat_lower': 290.5650040897352, 'yhat_upper': 573.9821456697384}, {'ds': '2021-05-30', 'yhat': 291.77825398281135, 'yhat_lower': 149.1715298031795, 'yhat_upper': 437.96087362690355}, {'ds': '2021-05-31', 'yhat': 329.28859536548924, 'yhat_lower': 198.3242776216241, 'yhat_upper': 476.2795125649486}, {'ds': '2021-06-01', 'yhat': 318.3233911429151, 'yhat_lower': 170.27466541677424, 'yhat_upper': 450.1187609446487}, {'ds': '2021-06-02', 'yhat': 236.17180350112815, 'yhat_lower': 94.91275243676972, 'yhat_upper': 377.99417261524553}, {'ds': '2021-06-03', 'yhat': 271.04041876872526, 'yhat_lower': 122.16539685452746, 'yhat_upper': 414.30728932366213}, {'ds': '2021-06-04', 'yhat': 423.1607676927503, 'yhat_lower': 285.4248200147331, 'yhat_upper': 561.227505157496}, {'ds': '2021-06-05', 'yhat': 422.63669592029026, 'yhat_lower': 282.8250934938295, 'yhat_upper': 565.533335505581}, {'ds': '2021-06-06', 'yhat': 279.21680195703783, 'yhat_lower': 145.24457009291936, 'yhat_upper': 428.0125119382632}, {'ds': '2021-06-07', 'yhat': 319.92625477477395, 'yhat_lower': 175.43183841351993, 'yhat_upper': 466.09363272847986}, {'ds': '2021-06-08', 'yhat': 312.4744122361378, 'yhat_lower': 165.04409832658675, 'yhat_upper': 465.5213051835357}, {'ds': '2021-06-09', 'yhat': 234.096249199177, 'yhat_lower': 94.32189035272003, 'yhat_upper': 384.8417312248711}, {'ds': '2021-06-10', 'yhat': 272.9394141700244, 'yhat_lower': 125.73482395581397, 'yhat_upper': 410.3993349650016}, {'ds': '2021-06-11', 'yhat': 429.1692833586484, 'yhat_lower': 282.9958387640418, 'yhat_upper': 567.6344929546925}, {'ds': '2021-06-12', 'yhat': 432.81690551593283, 'yhat_lower': 295.3222713339661, 'yhat_upper': 572.474057942829}, {'ds': '2021-06-13', 'yhat': 293.5579040962788, 'yhat_lower': 156.42308822380545, 'yhat_upper': 448.92402141973463}, {'ds': '2021-06-14', 'yhat': 338.3461563836069, 'yhat_lower': 192.88702012596792, 'yhat_upper': 468.2874817753597}, {'ds': '2021-06-15', 'yhat': 334.8149586455518, 'yhat_lower': 188.09277761285307, 'yhat_upper': 478.81138554221366}, {'ds': '2021-06-16', 'yhat': 260.1270459127901, 'yhat_lower': 120.14480738795396, 'yhat_upper': 406.100563929128}, {'ds': '2021-06-17', 'yhat': 302.36319142756395, 'yhat_lower': 168.44150445074592, 'yhat_upper': 441.1762018021081}, {'ds': '2021-06-18', 'yhat': 461.6250740348532, 'yhat_lower': 314.1146931602407, 'yhat_upper': 601.5791380121457}, {'ds': '2021-06-19', 'yhat': 467.8838260942634, 'yhat_lower': 325.2459932802357, 'yhat_upper': 617.2361034951167}, {'ds': '2021-06-20', 'yhat': 330.76517730574767, 'yhat_lower': 186.75972272455934, 'yhat_upper': 471.15772083394705}, {'ds': '2021-06-21', 'yhat': 377.1845276716698, 'yhat_lower': 237.6654659973457, 'yhat_upper': 519.6610488516261}, {'ds': '2021-06-22', 'yhat': 374.7409590562079, 'yhat_lower': 235.75669818150064, 'yhat_upper': 509.8918479018769}, {'ds': '2021-06-23', 'yhat': 300.57493214130625, 'yhat_lower': 155.09195178714498, 'yhat_upper': 437.86740509200405}, {'ds': '2021-06-24', 'yhat': 342.75732391145937, 'yhat_lower': 189.3771920750052, 'yhat_upper': 487.84540546744677}, {'ds': '2021-06-25', 'yhat': 501.3888419832906, 'yhat_lower': 356.99990490020843, 'yhat_upper': 649.0051935896033}, {'ds': '2021-06-26', 'yhat': 506.44778016090254, 'yhat_lower': 374.3339126357323, 'yhat_upper': 658.2901740546914}, {'ds': '2021-06-27', 'yhat': 367.579915028995, 'yhat_lower': 234.32147938561616, 'yhat_upper': 514.9970973150054}, {'ds': '2021-06-28', 'yhat': 411.7334280358476, 'yhat_lower': 262.6525234331041, 'yhat_upper': 560.8777727159763}, {'ds': '2021-06-29', 'yhat': 406.5442015720589, 'yhat_lower': 264.30245483775775, 'yhat_upper': 561.0446733439918}, {'ds': '2021-06-30', 'yhat': 329.1996526546736, 'yhat_lower': 188.85970747140803, 'yhat_upper': 467.6757265578845}, {'ds': '2021-07-01', 'yhat': 367.8267270009177, 'yhat_lower': 219.0683444096666, 'yhat_upper': 520.5465579864239}, {'ds': '2021-07-02', 'yhat': 522.5864733746628, 'yhat_lower': 380.9633102448831, 'yhat_upper': 660.201137498178}, {'ds': '2021-07-03', 'yhat': 523.5197469437801, 'yhat_lower': 384.3807206672481, 'yhat_upper': 670.081097149434}, {'ds': '2021-07-04', 'yhat': 380.34075467791735, 'yhat_lower': 243.88780328288343, 'yhat_upper': 522.2454031916853}, {'ds': '2021-07-05', 'yhat': 420.07090278589993, 'yhat_lower': 288.1241219764339, 'yhat_upper': 567.7605287204007}, {'ds': '2021-07-06', 'yhat': 410.4146529864544, 'yhat_lower': 276.07772807971236, 'yhat_upper': 537.9282229915591}, {'ds': '2021-07-07', 'yhat': 328.62898184908653, 'yhat_lower': 182.4743991165041, 'yhat_upper': 457.6298502497775}, {'ds': '2021-07-08', 'yhat': 362.9100416730033, 'yhat_lower': 216.4796310406674, 'yhat_upper': 508.2553266088901}, {'ds': '2021-07-09', 'yhat': 513.4828285816855, 'yhat_lower': 360.56584235475145, 'yhat_upper': 651.5790203202797}, {'ds': '2021-07-10', 'yhat': 510.44498735453067, 'yhat_lower': 363.14148376413823, 'yhat_upper': 649.3563606719416}, {'ds': '2021-07-11', 'yhat': 363.56437011783447, 'yhat_lower': 221.573015482064, 'yhat_upper': 507.6945710781028}, {'ds': '2021-07-12', 'yhat': 399.91237010032137, 'yhat_lower': 270.6080519564459, 'yhat_upper': 544.9069076848498}, {'ds': '2021-07-13', 'yhat': 387.23107653333693, 'yhat_lower': 250.1061916126753, 'yhat_upper': 533.270672128474}, {'ds': '2021-07-14', 'yhat': 302.8092524448842, 'yhat_lower': 158.30216991907918, 'yhat_upper': 444.19698829480046}, {'ds': '2021-07-15', 'yhat': 334.8686830630846, 'yhat_lower': 194.0681024665853, 'yhat_upper': 480.24706306510836}, {'ds': '2021-07-16', 'yhat': 483.6500573052659, 'yhat_lower': 326.3272446750951, 'yhat_upper': 632.1867230520788}, {'ds': '2021-07-17', 'yhat': 479.256061944585, 'yhat_lower': 342.72279627538285, 'yhat_upper': 611.5591078130184}, {'ds': '2021-07-18', 'yhat': 331.454178162093, 'yhat_lower': 190.3413127160067, 'yhat_upper': 478.90423329189787}, {'ds': '2021-07-19', 'yhat': 367.310731418865, 'yhat_lower': 223.80140266963716, 'yhat_upper': 514.9424700401192}, {'ds': '2021-07-20', 'yhat': 354.55054946966095, 'yhat_lower': 206.5438432276846, 'yhat_upper': 492.3452246788822}, {'ds': '2021-07-21', 'yhat': 270.44060894469334, 'yhat_lower': 122.18126927314582, 'yhat_upper': 416.374713183889}, {'ds': '2021-07-22', 'yhat': 303.1771411083788, 'yhat_lower': 160.77790442583574, 'yhat_upper': 450.37016877964453}, {'ds': '2021-07-23', 'yhat': 452.96869279708227, 'yhat_lower': 310.6398040602756, 'yhat_upper': 605.4666588621266}, {'ds': '2021-07-24', 'yhat': 449.98285695924386, 'yhat_lower': 308.46116189328126, 'yhat_upper': 599.0802433234941}, {'ds': '2021-07-25', 'yhat': 303.8383004351274, 'yhat_lower': 156.8541414809162, 'yhat_upper': 437.7048103826453}, {'ds': '2021-07-26', 'yhat': 341.56809279339734, 'yhat_lower': 188.57210168998535, 'yhat_upper': 490.2440096024441}, {'ds': '2021-07-27', 'yhat': 330.8528557115684, 'yhat_lower': 188.9100779141757, 'yhat_upper': 473.80669408886854}, {'ds': '2021-07-28', 'yhat': 248.91662084760924, 'yhat_lower': 112.99276141865882, 'yhat_upper': 389.2824084733628}, {'ds': '2021-07-29', 'yhat': 283.9149823623389, 'yhat_lower': 147.0614948214702, 'yhat_upper': 430.01365523197}, {'ds': '2021-07-30', 'yhat': 436.01532252714594, 'yhat_lower': 288.6793429482923, 'yhat_upper': 572.013974523274}]}